# Use the official Python image from the Docker Hub
FROM python:3.9-slim

# Set the working directory
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY ./frontend/client.py /app/

# Install the necessary packages
RUN pip install aiohttp

# Define the command to run the application
CMD ["python", "client.py"]
