# backend-deployment-and-service.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nimble-backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nimble-backend
  template:
    metadata:
      labels:
        app: nimble-backend
    spec:
      containers:
      - name: nimble-backend
        image: backend-image:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30001
  selector:
    app: nimble-backend
