apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: frontend-image
        imagePullPolicy: Never
        env:
        - name: BACKEND_URL
          value: "http://backend-service:8080"
        ports:
        - containerPort: 8080
