# frontend-deployment-and-service.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nimble-frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nimble-frontend
  template:
    metadata:
      labels:
        app: nimble-frontend
    spec:
      containers:
      - name: nimble-frontend
        image: frontend-image:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30002
  selector:
    app: nimble-frontend
